# -*- coding: utf-8 -*-
"""AlissonProjectNetflixData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqMveO9tGn-LAAaB-YHbdN2N6yGhcRvX
"""

#Import Libraries
import streamlit as st
import pandas as pd
import altair as alt
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('netflix_titles.csv')

#Page Configuration
st.set_page_config(
    page_title="US Population Dashboard",
    page_icon="🎬", # Clapperboard emoji
    layout="wide",
    initial_sidebar_state="expanded")

alt.themes.enable("dark")

#Add a sidebar for the selection of differents graphs
with st.sidebar:
    st.title('🎬 Netflix Data Visualization')

    graph_options = [
        "Release Year Distribution",
        "Distribution of Content Types",
        "Top 13 Countries with Most Content",
        "Trend of Releases Over Time",
        "Type vs Rating",
        "Filter Only Movies",
        "Pairplot",
        "Multivariate Analysis"
    ]
    selected_graph = st.selectbox('Select a Graph', graph_options)

def clean_data(df):
    required_columns = ['release_year', 'type', 'country', 'rating', 'duration']
    for column in required_columns:
        if column not in df.columns:
            st.error(f"La columna '{column}' no está presente en el DataFrame")
            return None

    df = df.dropna(subset=required_columns)
    return df

# Release Year Distribution
# Both movies and TV shows increased after 2010, peaking around 2018-2019.
def release_year_distribution(df):
    if df is None or df.empty:
        st.error("DataFrame is empty or not loaded properly.")
        return

    if 'release_year' not in df.columns:
        st.error("The column 'release_year' is missing from the DataFrame.")
        return

    fig, ax = plt.subplots(figsize=(10,6))

    sns.histplot(df['release_year'], color='r', kde=True, ax=ax)
    ax.set_title('Distribution of Release Years', size=18)
    ax.set_xlabel('Release Year', size=14)
    ax.set_ylabel('Density', size=14)

    st.pyplot(fig)

# Distribution of content types
# movies are dominated with more than 6000
def content_type_distribution(df):
    if df is None or df.empty:
        st.error("DataFrame is empty or not loaded properly.")
        return
    if 'type' not in df.columns:
        st.error("The column 'type' is missing from the DataFrame.")
        return
    fig, ax = plt.subplots(figsize=(10,6))
    sns.countplot(data=df, x='type', palette=['skyblue', 'orange'], ax=ax)
    ax.set_title('Count of Movies vs TV Shows on Netflix')
    st.pyplot(fig)

# Top 13 countries with most content
# we can notice that United States and India dominate both categories

def top_13_countries(df):
    if df is None or df.empty:
        return

    if 'country' not in df.columns:
        st.error("The column 'country' is missing from the DataFrame.")
        return

    fig, ax = plt.subplots(figsize=(10,6))
    top_countries = df['country'].value_counts().head(13)
    colors = ['skyblue', 'orange', 'green', 'red', 'purple', 'brown', 'pink', 'gray', 'olive', 'cyan', 'magenta', 'gold', 'lime']
    top_countries.plot(kind='bar', title='Top 13 Content Producing Countries', color=colors, ax=ax)
    ax.set_ylabel('Number of Titles')
    st.pyplot(fig)

# Trend of releases over time
# Around 2018 and 2019 are the years with the mist numbers of titles released over the period
def trend_of_releases(df):
    if df is None or df.empty:
        return

    fig, ax = plt.subplots(figsize=(12,5))
    df['release_year'].value_counts().sort_index().plot(kind='line', ax=ax, title='Number of Titles Released per Year')
    ax.set_xlabel('Year')
    ax.set_ylabel('Number of Titles')
    st.pyplot(fig)

# Type vs Rating
# we can notice that Movies are dominate in almost all catgories
#TV-MA is the most common rating overall, especially for TV Shows.
def type_vs_rating(df):
    if df is None or df.empty:
        return

    fig, ax = plt.subplots(figsize=(12,6))
    sns.countplot(data=df, x='rating', hue='type', order=df['rating'].value_counts().index, ax=ax)
    ax.set_title('Distribution of Ratings by Content Type')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45)
    ax.legend(title='Type')
    st.pyplot(fig)

# Filter only Movies
#Most Netflix movies are 90–110 minutes long
def filter_only_movies(df):
    if df is None or df.empty:
        return

    fig, ax = plt.subplots(figsize=(10,6))
    movies_df = df[df['type'] == 'Movie'].copy()
    movies_df['duration_minutes'] = movies_df['duration'].str.extract('(\d+)').astype(float)
    sns.histplot(data=movies_df, x='duration_minutes', bins=30, kde=True, ax=ax)
    ax.set_title('Distribution of Movie Durations (in minutes)')
    ax.set_xlabel('Duration (minutes)')
    st.pyplot(fig)

# Pairplot
# Extract duration in minutes (only works for movies)
def pairplot(df):
    if df is None or df.empty:
        return

    fig, ax = plt.subplots(figsize=(10,6))
    df['duration_minutes'] = df['duration'].str.extract('(\d+)').astype(float)
    df['type_encoded'] = df['type'].map({'Movie': 0, 'TV Show': 1})
    netflix_pairplot_df = df.dropna(subset=['release_year', 'duration_minutes', 'type_encoded'])

    sns.pairplot(
        netflix_pairplot_df[['release_year', 'duration_minutes', 'type_encoded']],
        markers="+",
        diag_kind="kde",
        kind='reg',
        plot_kws={
            'line_kws': {'color': '#aec6cf'},
            'scatter_kws': {'alpha': 0.7, 'color': 'red'}
        },
        corner=True
    )
    plt.suptitle('Netflix Titles Pairplot: Release Year, Duration, and Type (Encoded)', y=1.02)
    st.pyplot(fig)

# Multivariate Analysis
# release_year vs duration_minutes: Typically weak or no correlation expected.
# type_encoded vs duration_minutes: May show a negative correlation, since TV Shows don't usually have a numerical duration in minutes
# Ensure duration_minutes and type_encoded exist
def multivariate_analysis(df):
    if df is None or df.empty:
        return

    fig, ax = plt.subplots(figsize=(10,6))
    df['duration_minutes'] = df['duration'].str.extract('(\d+)').astype(float)
    df['type_encoded'] = df['type'].map({'Movie': 0, 'TV Show': 1})
    numerical_df = df[['release_year', 'duration_minutes', 'type_encoded']].dropna()

    sns.heatmap(numerical_df.corr(), annot=True, square=True, cmap='RdBu', vmin=-1, vmax=1, ax=ax)
    ax.set_title('Correlations Between Netflix Variables', size=18)
    ax.set_xticklabels(ax.get_xticklabels(), size=13)
    ax.set_yticklabels(ax.get_yticklabels(), size=13)
    st.pyplot(fig)

if df_cleaned is not None:
    if selected_graph == "Release Year Distribution":
        release_year_distribution(df_cleaned)
    elif selected_graph == "Distribution of Content Types":
        content_type_distribution(df_cleaned)
    elif selected_graph == "Top 13 Countries with Most Content":
        top_13_countries(df_cleaned)
    elif selected_graph == "Trend of Releases Over Time":
        trend_of_releases(df_cleaned)
    elif selected_graph == "Type vs Rating":
        type_vs_rating(df_cleaned)
    elif selected_graph == "Filter Only Movies":
        filter_only_movies(df_cleaned)
    elif selected_graph == "Pairplot":
        pairplot(df_cleaned)
    elif selected_graph == "Multivariate Analysis":
        multivariate_analysis(df_cleaned)